export const locale = {
    "locale": "bg-BG",
    "strings": {
        "newFormHeader": "Събитие",
        "editFormHeader": "Събитие - редакция",
        "newRecurrenceFormHeader": "Повторение",
        "editRecurrenceFormHeader": "Повторение - редакция",
        "cueFormHeader": "Скрити събития",
        "dateCaption": "Дата",
        "datesCaption": "Дати",
        "subjectCaption": "Заглавие",
        "startTimeCaption": "От",
        "endTimeCaption": "До",
        "allDayEventCaption": "Цял ден",
        "reminderCaption": "Напомняне",
        "detailsCaption": "Подробности",
        "contactsCaption": "Контакти",
        "todayCaption": "днес",
        "locationCaption": "Място",
        "patternCaption": "Повторение",
        "rangeCaption": "Период на повторение",
        "everyCaption": "всеки",
        "ofEveryCaption": "от всеки",
        "startCaption": "от",
        "noEndCaption": "без крайна дата",
        "endAfterCaption": "повторения",
        "endDateCaption": "до",
        "saveButtonCaption": "Запис",
        "optionsButtonCaption": "Детайли",
        "cancelButtonCaption": "Отказ",
        "recurrenceButtonCaption": "Повторения",
        "deleteButtonCaption": "Изтрий",
        "secondsValue": "секунди",
        "minuteValue": "минута",
        "minutesValue": "минути",
        "hourValue": "час",
        "hoursValue": "часа",
        "dayValue": "ден",
        "daysValue": "дни",
        "weeksValue": "седмици",
        "monthValue": "месец",
        "dailyValue": "Дневно",
        "weeklyValue": "Седмично",
        "monthlyValue": "Месечно",
        "yearlyValue": "Годишно",
        "intervalValue": "Интервал",
        "firstValue": "първи",
        "secondValue": "втори",
        "thirdValue": "трети",
        "fourthValue": "четвърти",
        "lastValue": "последен",
        "weekendValue": "почивен ден",
        "weekdayValue": "работен ден",
        "recurrenceDailyOnePattern": "Повторение всеки ден",
        "recurrenceDailyTwoPattern": "Повторение всеки [Days] дни",
        "recurrenceDailyThreePattern": "Повторение всеки работен ден",
        "recurrenceDailyFourPattern": "Повторение всеки почивен ден",
        "recurrenceWeeklyOnePattern": "Повторение всеки [DaysOfWeek]",
        "recurrenceWeeklyTwoPattern": "Повторение всяка [Weeks] седмица в [DaysOfWeek]",
        "recurrenceMonthlyOnePattern": "Повторение всяко [DayOfMonth] число от всеки [Months] месец",
        "recurrenceMonthlyTwoPattern": "Повторение всеки [Occurrence] [Day] от всеки [Months] месец",
        "recurrenceYearlyOnePattern": "Повторение всеки [DayOfMonth] [MonthOfYear]",
        "recurrenceYearlyTwoPattern": "Повторение всеки [Occurrence] [Day] от всеки [MonthOfYear]",
        "recurrenceIntervalPattern": "Повторение с интервал [Interval.Days] дни [Interval.Hours] часа [Interval.Minutes] минути [Interval.Seconds] секунди",
        "recurrenceStartDatePattern": "от [StartDate]",
        "recurrenceEndDatePattern": "до [EndDate]",
        "recurrenceTimeOnePattern": "от [StartTime] до [EndTime]",
        "recurrenceTimeTwoPattern": "в [StartTime]"
    }
};